<a href="https://colab.research.google.com/github/ordevoir/Data_Analysis/blob/main/numpy_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy <a href="https://numpy.org/"><img src="https://numpy.org/images/logo.svg" height="36"></a>

NumPy (Numerical Python) - это библиотека для языка программирования Python, предназначенная для работы с массивами данных и выполнения математических операций над ними.

NumPy предоставляет множество функций для выполнения операций линейной алгебры, обработки сигналов, обработки изображений и других вычислительных задач, которые требуют работу с массивами данных. Библиотека NumPy является основой для многих других библиотек, используемых в научных вычислениях и анализе данных, таких как Pandas, SciPy и Scikit-learn.

Одним из главных преимуществ NumPy является возможность выполнения вычислений над массивами данных с высокой производительностью. NumPy использует оптимизированные алгоритмы, написанные на языке программирования C, что позволяет ему обрабатывать большие объемы данных с высокой скоростью.

В NumPy определен многомерный массив (ndarray), который является основным объектом библиотеки. Этот объект представляет собой таблицу элементов (чисел), все из которых должны иметь одинаковый тип. NumPy также предоставляет функции для создания и манипулирования массивами данных, включая срезы (slicing), индексацию и изменение формы массивов. Подробности в [документации](https://numpy.org/doc/stable/).

Установить библиотеку NumPy в Python можно выполнив в терминале

`pip install numpy`

In [ ]:
import numpy as np

## Создание массивов

In [ ]:
x1 = np.array([1, 4, 6, 8])     # явное задание одномерного массива

# массив numpy можно создать из списка (list):
some_numeric_list = [5, 6, 7, 8]
x2 = np.array(some_numeric_list)    # создание массива из списка

print(x1, x2)
print('lenght:', len(x1))
print('type:', type(x1))
print('elements type:', x1.dtype)

[1 4 6 8] [5 6 7 8]
lenght: 4
type: <class 'numpy.ndarray'>
elements type: int32


In [ ]:
# создадим двумерный массив (матрицу) с задаыннм типом значений
x3 = np.array([
    [1, 4, 3, 2],
    [4, 5, 6, 3],
    [5, 1, 3, 7],
], dtype=np.float32)
print(x3)
print('array shape:', x3.shape)

[[1. 4. 3. 2.]
 [4. 5. 6. 3.]
 [5. 1. 3. 7.]]
array shape: (3, 4)


Здесь явно задан тип `float32`. Полный список доступных типов [здесь](https://numpy.org/doc/1.17/user/basics.types.html).

In [ ]:
# создадим массивы заданной формы, заполненные определенным значением
xZeros = np.zeros((2, 3))                   # заполнение нулями
xOnes = np.ones((2, 4))                     # заполнение единицами
xFull = np.full((2, 2), fill_value=7.0)     # заполнение числом 7

print('zeros:\n', xZeros)
print('\nones:\n', xOnes)
print('\nfull:\n', xFull)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

full:
 [[7. 7.]
 [7. 7.]]


In [ ]:
# можно задать массив, заполненный определенным числом, форма
# и тип значений которого повторяет форму и тип другого массива:

xOnesLike = np.ones_like(x3)
print('\nones like:\n', xOnesLike)

# есть также функции zeros_like, fill_like


ones like:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# создание диагональных матриц
xEye = np.eye(4, dtype=np.int16)    # значения по главной диагонали равны 1
xDiag = np.diag(v=(1, 2, 3, 4))

print('eye:\n', xEye)
print('\ndiag:\n', xDiag)

eye:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

diag:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
# можно задать массив состоящий из последовательности в заданном
# диапазоне с заданным шагом:
xArange = np.arange(10)             # задан только один аргумент
yArange = np.arange(5, 15, 2)
zArange = np.arange(15, 5, -2)

# первый аргумент: стартовное значение последовательности
# второй аргумент: финальное значение (не входит в последовательность)
# третий аргумент: шаг последовательности

print(xArange)
print(yArange)
print(zArange)

[0 1 2 3 4 5 6 7 8 9]
[ 5  7  9 11 13]
[15 13 11  9  7]


In [ ]:
# равномерно распределенные значения в заданном диапазоне
# с заданным число разбиения
xSpace = np.linspace(5, 15, 10)
print(xSpace)
print(xSpace.dtype)

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]
float64


Здесь приведены наиболее часто используемые способы создания массивов. Полный списко функций, создающих массивы [здесь](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation).

## Операции над массивами

### Умножение всех элементов массива на число

In [ ]:
# создадим первый массив:
a = np.array([
    [1, 2 ,3],
    [4, 5, 6],
    [7, 8, 9]
])
# второй массив создадим из первого, домножив его на 2:
b = a * 2
# второй массив будет результатом умножения всех элементов
# первого массива на число 2
print(b)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Поэлементные операции

In [ ]:
c = a + b
d = a * b

print('c:\n', c)
print('d:\n', d)

# подобным образом можно производить и поэлментное деление и вычитание

c:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
d:
 [[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


### Другие операции над массивами

In [ ]:
print(  c.min()     )      # значение минимального элемента
print(  c.max()     )      # значение максималаьного элемента
print(  c.sum()     )      # сумма всех элементов массива
print(  c.mean()    )      # среднее арифметическое от всех элементов

3
27
135
15.0


### Преобразование формы при помощи метода `reshape()`
Метод `reshape() `в классе `ndarray` библиотеки NumPy позволяет изменять форму (`shape`) массива без изменения его данных. Он возвращает новый массив с теми же данными, но с новой формой. Для этого нужно передать в качестве аргумента кортеж с новой формой. Количество элементов в массиве новой формы должно совпадать с количеством элементов исходного массива.

In [ ]:
a = np.array([
            [1,  2,  3,  4],
            [5,  6,  7,  8],
            [9, 10, 11, 12],
            ])
a.shape

(3, 4)

In [ ]:
a.reshape((4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a.reshape((2, 2, 3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Если в метод `reshape()` передать кортеж формы, содержащий значение `-1`, то это значение будет заменено на вычисленное автоматически значение, которое гарантирует, что общее количество элементов массива останется неизменным.

In [ ]:
a.reshape((2, -1))
# втрым значением формы будет 6:

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
a.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.reshape((-1, 1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

## Доступ к элментам массива по индексам

In [ ]:
print(c[2])     # доступ к строке с индексом 2
print(c[:, 1])  # доступ к столбцу с индексом 1
print(c[2, 0])  # доступ к элементу 2-ой строки 0-го столбца
c[0, 1] = 42    # изменение значения элемента 0-ой строки 1-го столбца

[21 24 27]
[ 6 15 24]
21


In [ ]:
# перебор всех элементов двумерного массива в цикле
for i in range(c.shape[0]):
    for j in range(c.shape[1]):
        print(c[i, j])

3
42
9
12
15
18
21
24
27


## Фильтрация массивов

In [ ]:
# операции сравнения
a = np.array([1, 2, 3, 3, 2, 1])
a == 2

array([False,  True, False, False,  True, False])

In [ ]:
print(a)
a_mask = (a <= 2)
print(a_mask)
extract = a[a_mask]
print(extract)

[1 2 3 3 2 1]
[ True  True False False  True  True]
[1 2 2 1]


In [ ]:
b = np.array([
    [1, 4, 3, 2],
    [4, 5, 6, 3],
    [5, 1, 3, 7],
], dtype=np.int8)
b.shape

(3, 4)

In [ ]:
mask = [True, False, True]
extracted = b[mask]
extracted

array([[1, 4, 3, 2],
       [5, 1, 3, 7]], dtype=int8)

In [ ]:
b[(0, 2), :]

array([[1, 4, 3, 2],
       [5, 1, 3, 7]], dtype=int8)

In [ ]:
mask = [True, False, True, False]
b[:, mask]

array([[1, 3],
       [4, 6],
       [5, 3]], dtype=int8)

In [ ]:
b[:, (0, 2)]

array([[1, 3],
       [4, 6],
       [5, 3]], dtype=int8)

In [ ]:
c = np.array([[ 0,  1,  2],     # row index 0
              [ 3,  4,  5],     # row index 1
              [ 6,  7,  8],     # row index 2
              [ 9, 10, 11]])    # row index 3

# составим массив из индексов строк массива c:
d = np.array([2, 1, 3, 1, 1, 2, 3])

e = c[d]

array([[ 6,  7,  8],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [ 3,  4,  5],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Массив `e` составлен из строк массива `c`, а число строк равно длине массива `d`. Строки в `e` выбраны из строк `c` в соответствии с индексами, представленными в `d`.